source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

# railsの起動時間を短縮する（標準gem）
gem "bootsnap", require: false

# MySQLに接続する
gem "mysql2", "~> 0.5"

# pumaサーバーを使えるようにする（標準gem）
gem "puma", "~> 5.0"

# rails本体（標準gem）
gem "rails", "~> 7.0.4"

# タイムゾーン情報を提供する（標準gem）
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

# cors設定を管理する
gem "rack-cors"

# 環境毎の設定管理を行う
gem "config"

# ユーザー認証を提供する
gem "devise"

# devise を日本語化する
gem "devise-i18n"

# ユーザーのトークン認証を提供する
gem "devise_token_auth"

# レスポンスJSONを制御する
gem "active_model_serializers"

group :development, :test do
  gem "letter_opener_web"
  # pry コンソールを使えるようにする。
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"
end